[package]
name = "cn-font-split"
description = "划时代的字体切割工具，CJK与任何字符！支持 otf、ttf、woff2 字体多线程切割，完美地细颗粒度地进行包大小控制。A revolutionary font subetter that supports CJK and any characters! It enables multi-threaded subset of otf, ttf, and woff2 fonts, allowing for precise control over package size."
version = "7.0.0"
edition = "2021"
authors = ["KonghaYao<3446798488@qq.com>"]
homepage = "https://chinese-font.netlify.app/"
repository = "https://github.com/konghaYao/cn-font-split"
license = "Apache-2.0"

[dependencies]
cn-font-utils = { version = "0.1.0", path = "crates/cn_font_utils" }
harfbuzz_rs_now = "2.2.5"
lang-unicodes = { version = "0.1.0", path = "crates/lang_unicodes" }
log = "0.4.22"
md5 = "0.7.0"
opentype = "0.38.0"
prost = "0.13.3"
cn-font-proto = { version = "0.1.1", path = "crates/proto" }
rayon = "1.10.0"
unicode-range = { version = "0.1.0", path = "crates/unicode_range" }
woff = "0.3.3"
current_platform = "0.2.0"
clap = { version = "4.5.22", features = ["derive"] }
chrono = "0.4.38"

[dev-dependencies]
env_logger = "0.11.5"


[build-dependencies]
cross = "0.2.5"
tonic-build = "0.12.3"

[workspace]
members = [
    "crates/cn_font_utils",
    "crates/lang_unicodes",
    "crates/proto",
    "crates/unicode_range",
    "packages/ffi",
    "packages/grpc",
    "packages/server",
    "packages/wasm-edge",
]

[profile.release]
lto = true

[[bin]]
name = "cn-font-split"
path = "./src/main.rs"
