[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
cn-font-split = { version = "7.0.0", path = "../.." }
axum = {version = "0.7.9", features = []}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.31"
tokio-stream = "0.1.16"
async-stream = "0.3.6"
futures-util = "0.3.31"
rust-s3 = "0.35.1"
cn-font-proto = { version = "0.1.0", path = "../../crates/proto" }
